version: '3.9' # optional since v1.27.0  --retirar

volumes:
  h2-data:

services:
  h2:
    container_name: 'h2'
    hostname: 'h2'
    image: code-challenge-ev/h2
    ports:
      - "8181:8182"
      - "1521:1521"
    volumes:
      - h2-data:/opt/h2-data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:${DB};DB_CLOSE_ON_EXIT=FALSE;CIPHER=AES
      - SPRING_DATASOURCE_DRIVER_CLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=SA
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_DATASOURCE_INITIALIZATION-MODE=always
      - SPRING_DATASOURCE_DATA=file:/usr/init-data/${DATA}

app:
  build: ./
  restart: on-failure
  depends_on:
    - h2
  image:
  container_name: code-challenge-ev-app
  volumes:
    - .:/var/lib/h2/data
  ports:
    - 80:8080
  links:
    - h2

##########postgres
#volumes: # como hds virtuais
#  code-challenge-ev-postgres-data:
#    driver: local

#services:
#  postgres:
#    image: postgres:14.2
#    container_name: code-challenge-ev-postgres
#    health-check:
#      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
#      timeout: 45s
#      interval: 10s
#      retries: 10
#    volumes:
#      - code-challenge-ev-postgres-data:/var/lib/postgresql/data
#    ports:
#      - 5432:5432 # porta local e remota respectivamente
#    restart: always
#    environment:
#      - POSTGRES_DB: code-challenge-ev
#      - POSTGRES_USER=ccev
#      - POSTGRES_PASSWORD=ccev